export const page = {
  home: '/user/me',
  signIn: '/signIn',
  qrCode: '/qrcode',
  qrCodePrint: '/qrcode/print',
  equipment: '/equipment',
  register: '/equipment/register',
  department: '/department',
  category: '/category',
  user: '/user',
  myPage: '/user/me',
  maintenance: '/maintenance',
  maintenanceDepartment: '/maintenance/department',
  maintenanceLocation: '/maintenance/location',
} as const;
