import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../../components/header';
import CustomizedTables from '../../components/table';
import styles from '../../styles/Home.module.css';
import { useEquipments } from '../../hooks/useEquipments';

const Equipment: NextPage = () => {
  const { equipments, isLoading, isError } = useEquipments();

  if (isError) return <div>Failed to load</div>;

  if (isLoading) return <div>Loading...</div>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <Header></Header>

      <main className={styles.main}>
        <CustomizedTables equipments={equipments} />
      </main>
    </div>
  );
};

export default Equipment;
