import type { NextPage } from 'next';
import Head from 'next/head';
import MainMenuCard from '../components/mainMenuCard';
import Header from '../components/header';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const cards = [
    { title: 'Monitor', src: '/images/monitor.svg', description: 'モニタ一覧を表示します。', path: '/qrcode' },
    { title: '貸出', src: '/images/rental.svg', description: '', path: '' },
    { title: '機器管理', src: '/images/computer.svg', description: 'PC一覧を表示します', path: '/equipment' },
    { title: 'ユーザ登録', src: '/images/user.svg', description: '', path: '' },
    { title: 'マスタ管理', src: '/images/master.svg', description: '', path: '' },
    {
      title: 'メンテナンス',
      src: '/images/maintenance.svg',
      description: 'Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica',
      path: '',
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <Header></Header>

      <main className={styles.main}>
        <div className={styles.grid}>
          {cards.map(x => (
            <MainMenuCard key={x.title} {...x} />
          ))}
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
