import type { NextPage } from 'next';
import Head from 'next/head';
import MenuAppBar from '../../components/header';
import CustomizedTables from '../../components/table';
import styles from '../../styles/Home.module.css';

const Equipment: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <MenuAppBar></MenuAppBar>

      <main className={styles.main}>
        <CustomizedTables />
      </main>
    </div>
  );
};

export default Equipment;
