import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ServiceCard from "../components/card";
import MenuAppBar from "../components/header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuAppBar></MenuAppBar>

      <main className={styles.main}>
        <div className={styles.grid}>
          <ServiceCard
            title="Monitor"
            src="/images/monitor.svg"
            description="aaaa"
          ></ServiceCard>
          <ServiceCard
            title="貸出"
            src="/images/rental.svg"
            description="bbbb"
          ></ServiceCard>
          <ServiceCard
            title="機器管理"
            src="/images/computer.svg"
            description="aaaa"
          ></ServiceCard>
          <ServiceCard
            title="ユーザ登録"
            src="/images/monitor.svg"
            description="aaaa"
          ></ServiceCard>
          <ServiceCard
            title="マスタ管理"
            src="/images/monitor.svg"
            description="aaaa"
          ></ServiceCard>
          <ServiceCard
            title="メンテナンス"
            src="/images/maintenance.svg"
            description="aaaa"
          ></ServiceCard>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
