import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import ServiceCard from '../components/card';
import MenuAppBar from '../components/header';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const router = useRouter();

  const cards = [
    { title: 'Monitor', src: '/images/monitor.svg', description: 'aaa', path: '/qrcode' },
    { title: '貸出', src: '/images/rental.svg', description: 'aaa', path: '' },
    { title: '機器管理', src: '/images/computer.svg', description: 'aaa', path: '' },
    { title: 'ユーザ登録', src: '/images/user.svg', description: 'aaa', path: '' },
    { title: 'マスタ管理', src: '/images/master.svg', description: 'aaa', path: '' },
    { title: 'メンテナンス', src: '/images/maintenance.svg', description: 'aaa', path: '' },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <MenuAppBar></MenuAppBar>

      <main className={styles.main}>
        <div className={styles.grid}>
          {cards.map(x => (
            <ServiceCard {...x} />
          ))}
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
